### ISSUE TITLE
signature format, or what am i doing wrong?

### ISSUE THREAD

**Issue by faried** [libitx/curvy#1]
I'm working with some code that uses the [elliptic](https://github.com/indutny/elliptic) package to sign messages.  I am unable to recover the same public keys from the message signatures with Curvy that I can with elliptic.  I've confirmed that I can use something else like [ex_secp256k1](https://hex.pm/packages/ex_secp256k1) to get the same key.

I have some sample code in a [gist](https://gist.github.com/faried/2e2cb216ccf9f4238dd21f1156547b17).

What I get over the wire is a message signature encoded in hex, in this format:

* one byte for the recovery parameter
* 32 bytes for r
* 32 bytes for s

In my case,

* recid: 1
* r: `"5a86f1cfef1edd63aa7f1adaee39e5b4a5b8fc6046eab6def8892c5d46910b52"`
* s: `"4b3e0bedfd39e67abdca3fa9075231a809973fdf10a7568315803d2a9bebc148"`

The message that is signed: `"dc85768cf272d8245cce1ae289b3652e25bc415277898a5e4c93d66a881e180d"`

I do
```elixir
message = Base.decode16!("dc85768cf272d8245cce1ae289b3652e25bc415277898a5e4c93d66a881e180d", case: :lower)
r = Base.decode16!("5a86f1cfef1edd63aa7f1adaee39e5b4a5b8fc6046eab6def8892c5d46910b52", case: :lower)
s = Base.decode16!("4b3e0bedfd39e67abdca3fa9075231a809973fdf10a7568315803d2a9bebc148", case: :lower) 
sig = %Curvy.Signature{r: :binary.decode_unsigned(r), s: :binary.decode_unsigned(s), recid: 1}
pubkey = Curvy.recover_key(sig, message, recovery_id: 1)
Curvy.Key.to_pubkey(pubkey, compressed: true) |> Base.encode16(case: :lower)
```
I get `"02393f94975f56dad52554004726804c70879de81417ce19426e78f750e47736e8"`

This is different from the public key that I expect -- `"0316b9dc66ec8b319b3d0a0ed0ec2ed433ab080f72c43fac6d51f48a0b8696e832"`

**Comment by libitx** [comment]
Apologies - only just noticed this issue. Will take a look this week and get back to you.

**Comment by libitx** [comment]
@faried ah I see...

Curvy by default always hashes the message with `sha256` - in your case it looks like the message is already hashed. We don't want to hash it again so can pass `hash: false` to `recover_key`:

```elixir
Curvy.recover_key(sig, message, recovery_id: 1, hash: false)
```

That will give you: `0316b9dc66ec8b319b3d0a0ed0ec2ed433ab080f72c43fac6d51f48a0b8696e832`

**Comment by faried** [comment]
Thanks!  That solves my problem.

If it's not too much of a bother, can you describe how you found the solution?

**Comment by libitx** [comment]
Sure. I could see that the message you were providing in your example above was a 32 byte hexadecimal string, so there was a reasonable chance it was already a hash. I know that curvy hashes messages automatically so in all likelihood the reason for your discrepancy was because Curvy was hashing what was already a hash and the other software you were comparing against was not doing that.
