### ISSUE TITLE
Different hashes produced in comparison to other signers

### ISSUE THREAD

**Issue by qcam** [libitx/curvy#3]
First off, thanks for the library!

I'm trying out Curvy and realized that the hash produced was different from the hashes generated by `libsecp256k1`.

This sample for example generates totally different 

```ex
private_key = Base.decode16!("8da4ef21b864d2cc526dbdb2a120bd2874c36c9d0a1fb7f8c63d7f7a8b41de8f", case: :lower)
message = <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2>>

ExSecp256k1.sign(msg, private_key)
{:ok,
 {<<73, 102, 23, 43, 29, 88, 149, 68, 77, 65, 248, 57, 200, 155, 43, 249, 154,
    95, 100, 185, 121, 244, 84, 178, 159, 90, 254, 45, 27, 177, 221, 218>>,
  <<21, 214, 167, 20, 61, 86, 189, 86, 241, 39, 239, 70, 71, 66, 201, 140, 21,
    23, 206, 201, 129, 255, 24, 20, 160, 152, 36, 114, 115, 245, 33, 208>>, 1}}

Curvy.sign(msg, private_key)
<<48, 68, 2, 32, 112, 250, 91, 30, 30, 158, 220, 214, 106, 47, 254, 129, 4, 155,
  57, 80, 10, 104, 105, 84, 11, 30, 228, 232, 180, 55, 35, 240, 18, 139, 224,
  87, 2, 32, 80, 240, 185, 198, 24, 162, 98, 109, 119, 126, 246, 190, ...>>
```

Did I maybe miss out some options or any configuration? Any help would be very appreciated. Thanks.

**Comment by libitx** [comment]
By default Curvy will hash the given message with `sha256`. libsecp256k1 assumes you have already hashed the message and are giving it a 32 byte digest.

You can chose for Curvy to not hash the message by using the `hash: false` option.

```elixir
Curvy.sign(message, private_key, hash: false)
<<48, 68, 2, 32, 73, 102, 23, 43, 29, 88, 149, 68, 77, 65, 248, 57, 200, 155,
  43, 249, 154, 95, 100, 185, 121, 244, 84, 178, 159, 90, 254, 45, 27, 177, 221,
  218, 2, 32, 21, 214, 167, 20, 61, 86, 189, 86, 241, 39, 239, 70, ...>>
```

Note that Curvy is returning a DER-encoded signature here whereas ExSecp256k1 is returning a tuple in the format: {:ok, r, s, recovery_id}. But the signature is indeed the same.

**Comment by qcam** [comment]
@libitx Thank you for the help 🙏.
